# Pandas Deep-Dive

#### 1. Import Pandas package under the alias pd and Numpy under the alias np.

In [1]:
# your code here

import pandas as pd
import numpy as np

#### 2. Define a variable called `path` that contains the path to the csv file you downloaded. If you are reading the data from Ironhack's database, define the variables needed to create the connection with the database. 

In [2]:
# your code here

path = 'https://raw.githubusercontent.com/renatorbf/lab-pandas-deep-dive/master/your-code/apple_store.csv'

#### 3. Using the pandas, read the data either from the downladed file or the database. 

Assign the returned value to a variable called `data`.

In [3]:
# your code here

data = pd.read_csv(path)

#### 4. Print the first 5 rows of `data` to see what the data look like.

A data analyst usually does this to have a general understanding about what the data look like before digging deep.

In [33]:
# your code here
data.head()

id  ...     guess
0  281656475  ...  84955.08
1  281796108  ...      0.00
2  281940292  ...      0.00
3  282614216  ...      0.00
4  282935706  ...      0.00

[5 rows x 10 columns]

#### 5. Print the summary of the data.

In [5]:
# your code here

data.describe()

id    size_bytes  ...  user_rating  user_rating_ver
count  7.197000e+03  7.197000e+03  ...  7197.000000      7197.000000
mean   8.631310e+08  1.991345e+08  ...     3.526956         3.253578
std    2.712368e+08  3.592069e+08  ...     1.517948         1.809363
min    2.816565e+08  5.898240e+05  ...     0.000000         0.000000
25%    6.000937e+08  4.692275e+07  ...     3.500000         2.500000
50%    9.781482e+08  9.715302e+07  ...     4.000000         4.000000
75%    1.082310e+09  1.819249e+08  ...     4.500000         4.500000
max    1.188376e+09  4.025970e+09  ...     5.000000         5.000000

[8 rows x 7 columns]

#### 6. Print the number of columns in the data.

In [27]:
# your code here
len(data.columns)

9

#### 7. Print all column names.

In [7]:
# your code here
data.columns

Index(['id', 'track_name', 'size_bytes', 'price', 'rating_count_tot',
       'rating_count_ver', 'user_rating', 'user_rating_ver', 'prime_genre'],
      dtype='object')

#### 8.- Now that we have a general understanding of the data, we'll start working on the challenge questions. How many apps are there in the data source? Print the number of observations of the data.

**Hint**: Your code should return the number 7197.

In [8]:
# your code here
data.count()

id                  7197
track_name          7197
size_bytes          7197
price               7197
rating_count_tot    7197
rating_count_ver    7197
user_rating         7197
user_rating_ver     7197
prime_genre         7197
dtype: int64

#### 9. What is the average rating of all apps? 

First, read the `user_rating` column into a varialbe named `user_rating`.

In [9]:
# your code here
user_rating = data['user_rating']

Now you can calculate the average of the `user_rating` data.

**Hint**: Your code should return 3.526955675976101.

In [10]:
# your code here
user_rating.mean()

3.526955675976101

#### 10. How many apps have an average rating no less than 4?

First, filter `user_rating` where its value >= 4. 

Assign the filtered dataframe to a new variable called `user_rating_high`.

In [11]:
# your code here
# user_rating_high = data[data[('user_rating')] >= 4]
user_rating_high = user_rating[user_rating >= 4]
#both work
user_rating_high

0       4.0
1       4.0
3       4.0
4       4.5
5       4.0
       ... 
7192    4.5
7193    4.5
7194    4.5
7195    4.5
7196    5.0
Name: user_rating, Length: 4781, dtype: float64

Now obtain the length of `user_rating_high` which should return 4781.

In [12]:
# your code here
len(user_rating_high)

4781

#### 11. How many genres are there in total for all the apps?

Define a new variable named `genres` that contains the `prime_genre` column of `data`. Google for how to obtain unique values of a dataframe column. 

In [13]:
# your code here
genres = data['prime_genre']

Print the length of the unique values of `genres`. Your code should return 23.

In [14]:
# your code here
# len(genres.unique())
genres.nunique()

# both work

23

#### 12. What are the top 3 genres that have the most number of apps?

What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution. Your code should return the following:

```
Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64
```

In [15]:
# your code here
data.value_counts('prime_genre').head(3)

prime_genre
Games            3862
Entertainment     535
Education         453
dtype: int64

#### 13. Which genre is most likely to contain free apps?

First, filter `data` where the price is 0.00. Assign the filtered data to a new variable called `free_apps`. Then count the values in `free_apps`. Your code should return:

```
Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Navigation             20
Reference              20
Business               20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64
```

In [16]:
# your code here
free_apps = data[data['price'] == 0]

#### 14. Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps. 

Challenge yourself by achieving that with one line of code. The output should look like:

```
Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64
```

The numbers are interesting, aren't they?

In [17]:
# your code here
(free_apps['prime_genre'].value_counts()/data.value_counts('prime_genre'))

# it's not sorted

Book                 0.589286
Business             0.350877
Catalogs             0.900000
Education            0.291391
Entertainment        0.624299
Finance              0.807692
Food & Drink         0.682540
Games                0.584412
Health & Fitness     0.422222
Lifestyle            0.652778
Medical              0.347826
Music                0.485507
Navigation           0.434783
News                 0.773333
Photo & Video        0.478510
Productivity         0.348315
Reference            0.312500
Shopping             0.991803
Social Networking    0.856287
Sports               0.692982
Travel               0.691358
Utilities            0.439516
Weather              0.430556
dtype: float64

#### 15. If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.

We will leave this question to you. There are several way to solve it. Ideally your output should look like below:

```
    average_price              genre
21       8.776087            Medical
11       5.116316           Business
4        4.836875          Reference
6        4.835435              Music
1        4.330562       Productivity
15       4.124783         Navigation
16       4.028234          Education
12       1.916444   Health & Fitness
20       1.790536               Book
7        1.647621          Utilities
2        1.605417            Weather
18       1.552381       Food & Drink
14       1.473295      Photo & Video
0        1.432923              Games
8        1.120370             Travel
10       0.953070             Sports
13       0.889701      Entertainment
17       0.885417          Lifestyle
22       0.799000           Catalogs
19       0.517733               News
5        0.421154            Finance
9        0.339880  Social Networking
3        0.016311           Shopping
```

In [45]:
# your code here

# i am going to try to guess the mean gross revenue by genre
# i am assuming that the rating_count_tot are proportional to the the downloads

data['guess'] = data['price'] * data['rating_count_tot']

# now let's group the data by genre
data.groupby(['prime_genre']).agg({'guess':'mean'}).sort_values(by=['guess'], ascending=False)

# i would advise the business genre

guess
prime_genre                    
Business           12875.321930
Productivity       10004.258708
Music               9373.717174
Weather             6888.404861
Games               6786.851455
Reference           5726.806875
Medical             5646.062609
Health & Fitness    5038.194722
Navigation          3817.208478
Photo & Video       3212.148596
News                2490.179733
Utilities           2151.712621
Education           2035.438962
Entertainment       1382.187869
Catalogs            1045.891000
Lifestyle            924.060208
Book                 807.101875
Food & Drink         756.010794
Travel               706.520000
Finance              392.520577
Sports               258.010439
Social Networking    234.710539
Shopping              44.399836

# Challenge - Applying Functions to DataFrames

#### Our next step is to use the apply function to a dataframe and transform all cells.

To do this, we will load a dataset below and then write a function that will perform the transformation.

In [19]:
# Run this code:

# The dataset below contains information about pollution from PM2.5 particles in Beijing 

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00381/PRSA_data_2010.1.1-2014.12.31.csv"
pm25 = pd.read_csv(url)

Let's look at the data using the head() function.

In [20]:
# Your code here:

pm25.head()

No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

The next step is to create a function that divides a cell by 24 to produce an hourly figure. Write the function below.

In [21]:
def hourly(x):
    '''
    Input: A numerical value
    Output: The value divided by 24
        
    Example:
    Input: 48
    Output: 2.0
    '''
    
    # Your code here:
    return x/24

Apply this function to the columns Iws, Is, and Ir. Store this new dataframe in the variable pm25_hourly.

In [22]:
# Your code here:
pm25_hourly = pm25.copy()

pm25_hourly['Iws'] = pm25['Iws'].apply(hourly)
pm25_hourly['Is'] = pm25['Is'].apply(hourly)
pm25_hourly['Ir'] = pm25['Ir'].apply(hourly)

pm25_hourly

No  year  month  day  hour  ...    PRES  cbwd        Iws   Is   Ir
0          1  2010      1    1     0  ...  1021.0    NW   0.074583  0.0  0.0
1          2  2010      1    1     1  ...  1020.0    NW   0.205000  0.0  0.0
2          3  2010      1    1     2  ...  1019.0    NW   0.279583  0.0  0.0
3          4  2010      1    1     3  ...  1019.0    NW   0.410000  0.0  0.0
4          5  2010      1    1     4  ...  1018.0    NW   0.540417  0.0  0.0
...      ...   ...    ...  ...   ...  ...     ...   ...        ...  ...  ...
43819  43820  2014     12   31    19  ...  1034.0    NW   9.665417  0.0  0.0
43820  43821  2014     12   31    20  ...  1034.0    NW   9.907500  0.0  0.0
43821  43822  2014     12   31    21  ...  1034.0    NW  10.112500  0.0  0.0
43822  43823  2014     12   31    22  ...  1034.0    NW  10.280000  0.0  0.0
43823  43824  2014     12   31    23  ...  1034.0    NW  10.410417  0.0  0.0

[43824 rows x 13 columns]

#### Our last challenge will be to create an aggregate function and apply it to a select group of columns in our dataframe.

Write a function that returns the standard deviation of a column divided by the length of a column minus 1. Since we are using pandas, do not use the `len()` function. One alternative is to use `count()`. Also, use the numpy version of standard deviation.

In [23]:
def sample_sd(x):
    '''
    Input: A Pandas series of values
    Output: the standard deviation divided by the number of elements in the series
        
    Example:
    Input: pd.Series([1,2,3,4])
    Output: 0.3726779962
    '''
    
    # Your code here:
    # x is the column
    col_std = np.std(x)
    divider = x.count() - 1
    return col_std / divider

In [24]:
sample_sd(data['price'])

0.0008105337040270615